---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: db-deployment
  namespace: aks-learning
spec:
  serviceName: db-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      terminationGracePeriodSeconds: 10
      
      containers:
      - name: sql2017
        image: microsoft/mssql-server-linux
        imagePullPolicy: IfNotPresent
        ports:
        - name: dbport
          containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: AKSLearn(!)
          # valueFrom:
            # secretKeyRef:
              # name: sqlsecret
              # key: sapassword
        - name: MSSQL_PID
          value: Developer