---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: akslearndb-data
  namespace: aks-learning-azure
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi